#!/usr/bin/env bash
# run nginx as "nginx" user and should listen in port 8080
pkill apache2
sed -i "s/80 default_server/8080 default_server/" /etc/nginx/sites-available/default
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
